// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo-6Qe2t8C4NwZDpvpO38Su-xZfcVzdxM',
    appId: '1:448732648895:web:c1697f6f25d1f2d5117d0a',
    messagingSenderId: '448732648895',
    projectId: 'drone-delivery-app-1acd6',
    authDomain: 'drone-delivery-app-1acd6.firebaseapp.com',
    storageBucket: 'drone-delivery-app-1acd6.firebasestorage.app',
    measurementId: 'G-7WSY9MGT7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWTwpESrRNInEpmfCJGryBtQM8o8v6sI',
    appId: '1:448732648895:android:5d0628d79b5ff927117d0a',
    messagingSenderId: '448732648895',
    projectId: 'drone-delivery-app-1acd6',
    databaseURL: 'https://drone-delivery-app-1acd6-default-rtdb.firebaseio.com',
    storageBucket: 'drone-delivery-app-1acd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4zVygnj_E7cpa6WhrdOrqVpb0jrmvvhc',
    appId: '1:448732648895:ios:9cc7c6c42851af8d117d0a',
    messagingSenderId: '448732648895',
    projectId: 'drone-delivery-app-1acd6',
    databaseURL: 'https://drone-delivery-app-1acd6-default-rtdb.firebaseio.com',
    storageBucket: 'drone-delivery-app-1acd6.firebasestorage.app',
    androidClientId:
        '448732648895-1dk8p207l7q0bu0kcoeamqugk36dv09l.apps.googleusercontent.com',
    iosClientId:
        '448732648895-t6gsro0q4ehfgu1rlgs5m29m216m7jp8.apps.googleusercontent.com',
    iosBundleId: 'com.xrone.pilot',
  );
}
